### ISSUE TITLE
java.lang.NullPointerException: intent's action must be set

### ISSUE THREAD

**Issue by Mouadabdelghafouraitali** [marcoscgdev/shortcut-helper#4]
**Android Version : 8.0**

i'm trying to add list of shortcut 

```
 public void shortcuts() {
        List<Shortcut> shortcutList = new ArrayList<Shortcut>();
        Intent removeads = new Intent(Intent.ACTION_VIEW, Uri.parse("URL"));
        shortcutList.add(new Shortcut("Remove ", "Remove ", R.drawable.gift, removeads));
        shortcutList.add(new Shortcut("Favorite", "Favorite", R.drawable.ic_remove, new Intent(this, FavoriteActivity.class)));
        shortcutList.add(new Shortcut("Quotes Maker", "Quotes Maker", R.drawable.quotesmaker_white, new Intent(this, QuotesMaker.class)));
        shortcutList.add(new Shortcut("Mini Editor", "Mini Editor", R.drawable.editor, new Intent(this, Editor_Page.class)));
        ShortcutHelper.with(MainActivity.this)
                .createShortcutList(shortcutList)
                .go();
    }
```

but i get this error : 

```
 Caused by: java.lang.NullPointerException: intent's action must be set
        at com.android.internal.util.Preconditions.checkNotNull(Preconditions.java:128)
        at android.content.pm.ShortcutInfo$Builder.setIntents(ShortcutInfo.java:1012)
        at android.content.pm.ShortcutInfo$Builder.setIntent(ShortcutInfo.java:991)
        at com.marcoscg.shortcuthelper.ShortcutHelper.createShortcutList(ShortcutHelper.java:78)
        at maa.pixelwavewallpapers.Activities.MainActivity.shortcuts(MainActivity.java:360)
        at maa.pixelwavewallpapers.Activities.MainActivity.onCreate(MainActivity.java:88)
```

**Comment by marcoscgdev** [comment]
You have entered a wrong "activity" intent method.
```
Intent intent = new Intent(this, FavoriteActivity.class);
```

You must create activity intents like this one:

```
Intent intent = new Intent(Intent.ACTION_MAIN, Uri.EMPTY, this, FavoriteActivity.class).setFlags(Intent.FLAG_ACTIVITY_CLEAR_TASK);
```
